name: Notquitelikeme Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: notquitelikeme/notquitelikeme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_66d9f734-94aa-4afe-aae4-b4f7dfa3aac5 }}
          GH_TOKEN: ${{ secrets.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 }}
